#!/system/bin/sh

dir=$(realpath "${0%/*}")
cd "$dir" || exit 1

log -p i -t "LSPosed" "starting lspd $*"
./lspd >/dev/null 2>&1 &
PID=$!
log -p i -t "LSPosed" "started lspd $PID"
wait $PID
rc=$?

if [ $rc -ne 0 ]; then
    log -p e -t "LSPosed" "lspd $PID exited unexpectedly, code=$rc"
    mkdir -p /data/adb/lspd/log
    logcat -b all -f "/data/adb/lspd/log/daemon-$PID-crash-$(date -Iseconds).log" -t 100000 -v uid
fi
